### ISSUE TITLE
Configurable release name to create a timestamp folder

### ISSUE THREAD

**Issue by osrecio** [staempfli/magento2-deployment-tool#2]
In file: https://github.com/staempfli/magento2-deployment-tool/blob/master/build/xmlscripts/release.xml#L63 

You have:

```
<contains string="${release.version}" substring="develop" casesensitive="false"/>
```

Can be changed the `substring` for configurable property? In this way you can specify the branch that should create a folder timestamps (in our case can be dev/staging). Something to configure in `config/project.properties` or `deployment-settings/project.properties`

Thanks!

**Comment by jalogut** [comment]
Sure, would you like to create a PR for that? The variable could be called `snapshot.branch` or `ci.branch`. The default value for this parameter in `build/config/default.properties` will be `develop`

**Comment by osrecio** [comment]
Yes i will create a PR tomorrow, I like more the name: `ci.branch`.

Thanks!

**Comment by osrecio** [comment]
Finally used `snapshot.branch` I think has more sense.

**Comment by jalogut** [comment]
Enhancement added on version 2.1
